### ISSUE TITLE
Massage when adding a new device

### ISSUE THREAD

**Issue by JohanLeirnes** [noctarius/lightify-binary-protocol#1]
Have you scanned a massage when adding a new device. I'm trying to add a device that is found by the gateway and Osrams API. But it does not show up in the app. It's a new IKEA Tradfri and im guessing that it's because of a wierd letter in the name of the E27 bulb.

**Comment by JohanLeirnes** [comment]
This is the bulb I'm trying to name:

"modelName":"TRADFRI bulb E27 WS�opal 980lm"

Compared to another that shows up and can be namned:

"modelName":"TRADFRI bulb E14 WS opal 400lm"

Both can be controlled with this binary protocol and via Osram API.

**Comment by JohanLeirnes** [comment]
So spoofing a message that gives the device a name would be greatly appreciated

**Comment by noctarius** [comment]
Did you try to capture the packet coming from the gateway? The text might have a different encoding over UTF-8?

PS: a captured packet would be cool as the status information might be different

**Comment by JohanLeirnes** [comment]
I am in the middle of a move so most of stuff is packed up and will not have it available for a couple of weeks. Just thought if you had the time you could scan setting up a device since you know what you are doing :)

**Comment by noctarius** [comment]
The bulbs will be available from April in Germany, I'll try to get a few. Guess I have no E14 sockets nut E27 :-)

I think lightify and hue gateways are not yet officially supported but they seem to work mostly. 

How does the tunable white work? Is it seamless or is it 3 settings that can be changed?

**Comment by noctarius** [comment]
Ok just bought a Tradfri lamp and it seems the newer bulbs have a different default name. The device is called "Device 1" but I'll need to put some more investigation into the captured packets first to be like 100% sure. Maybe the app just couldn't make any sense of the name (because of the weird encoding) and decided to rename it to "Device 1" :)

**Comment by JohanLeirnes** [comment]
There has been alot of updates to the lamp in firmware If you have a gateway the old bulbs light might get an update that reflects your findings.

**Comment by noctarius** [comment]
Nah don't have a Tradfri gateway, just the Lightify one, sorry :)

I wonder if Tradfri bulbs get the updates using a Lightify gateway too ;)

**Comment by JohanLeirnes** [comment]
What I meant was that the older devices might show up as Device 1 once they are updated. Newer bulbs probably come loaded with the latest version out of the box

**Comment by noctarius** [comment]
Not sure, just bought it today, cannot update it ;) Anyhow the OSRAM app thinks the bulb is not dimmable but the gateway recognizes the commands and the bulb acts accordingly :)

**Comment by JohanLeirnes** [comment]
I have a new bulb now and a motion detector, the gateway finds them both but are unable to figure out what the motion detector is. 

have you got a motion detector or remote to test with if you can get them to work?

[{"deviceId":1,"deviceType":"LIGHT","manufacturer":"OSRAM","modelName":"TRADFRI bulb E27 opal 1000lm","name":"Pannrummet","groupList":[1],"bmpClusters":null,"online":0,"on":1,"brightnessLevel":1.0,"hue":303.75,"saturation":1.0,"temperature":0,"firmwareVersion":"11105720","color":"10000F"},{"deviceId":2,"deviceType":"LIGHT","manufacturer":"OSRAM","modelName":"TRADFRI motion sensor","name":null,"groupList":[],"bmpClusters":null,"online":0,"on":1,"brightnessLevel":1.0,"hue":303.75,"saturation":1.0,"temperature":0,"firmwareVersion":"11115720","color":"10000F"}]%

**Comment by noctarius** [comment]
Scary that all Tradfri devices seem to use completely different device types than the official Lightify ones. I have 3 Tradfri bulbs myself right now (not a motion detector) and 2 work but the 3rd one is not really recognized. Have the Tradfri bridge here as well, so maybe I have to update the firmware. 

You probably have to retrieve the status of the motion sensor in a loop while waving in front but it definitely seem to work differently from the Lightify one.

**Comment by noctarius** [comment]
Is there any new finding from your side @bhaap? :)
