### ISSUE TITLE
Device Type

### ISSUE THREAD

**Issue by xconsult** [noctarius/lightify-binary-protocol#2]
4 = OSRAM LIGHTIFY Classic A LED-Glühlampe, 10 Watt, E27, klar, dimmbar / warmweiß 2700K

**Comment by noctarius** [comment]
Hm also scheinbar kein Bitfield =/ Naja schade :) Danke

**Comment by xconsult** [comment]
64 = Switch 2 Tasten
65 = Switch 4 Tasten

**Comment by noctarius** [comment]
Cool, besten Dank. Ist eingepflegt!

**Comment by xconsult** [comment]
Gerne! wobei der 2 Button Switch im Prinzip ein Dimmer ist

**Comment by noctarius** [comment]
Hab das Ding noch nie in der Hand gehabt, "im Prinzip ein Dimmer" meint was? Nur heller / dunkler? Und der 4-Taster hat noch was extra?

**Comment by noctarius** [comment]
PS: Du kannst auch direkt Pull Requests mit Änderungen am Text schicken :)
