### ISSUE TITLE
Are there Events/Signals

### ISSUE THREAD

**Issue by deisi** [noctarius/lightify-binary-protocol#4]
Thx for the amazing work in documenting this protocol for everybody. 

I'm thinking about writing a re-implementation of this protocol in python. Over at HomeAssistant.io we currently use a not very flexible implementation of the protocol, that currently limits our capabilities there. https://github.com/tfriedel/python-lightify

I was wondering if it is possible to receive signals/events from the gateway. The reason are switches. If there is no kind of event outside of the gateway itself, there is little reason to implement switches at all. The magic either happens within the gateway and just works, or one would explicitly need to ask for the state of the switch every 100ms or so, and I don't think this is what this protocol is made for.

**Comment by noctarius** [comment]
Hey @deisi, sorry for the late answer. As of now I'm not aware of any event streams that be available from the gateway. Last time I looked at the Lightify App it was also polling the device states at regular intervals.

Switches and their events seem to be handled only inside the gateway and not inside the app, which kind of makes sense to make sure they're switched even if no app is in range (and hopefully it is done locally and not with a timer in the cloud ;-))

**Comment by deisi** [comment]
Thx for the answer. Sad to hear that there is no such thing. I close this for now.
