### ISSUE TITLE
Incorrect/incomplete commands for scenes

### ISSUE THREAD

**Issue by OleksandrBerchenko** [noctarius/lightify-binary-protocol#5]
1. 0x1F actually returns the list of scenes (much like 0x1E for groups).  Result has the following format:

[bytes 0:6: header][bytes 7:8: number of scenes][byte 9: scene ID][byte 10: @ symbol][byte 11:26: scene name][bytes 27:28: unknown][byte 29: next scene ID]...

2. 0x52 (PACKET_ACTIVATE_SCENE) is a global command, it requires scene ID as byte 8, \x00 for up to byte 15 and nothing more.

Thanks!

**Comment by noctarius** [comment]
Thanks @OleksandrBerchenko! Changed and added the information according to your findings. Can you have a quick look to see if it is correct?

I close it for now, feel free to reopen or send a PR if something is wrong.

**Comment by OleksandrBerchenko** [comment]
```
0-1 Number of Scenes
```

Actually it should be 7-8.

Thanks!

**Comment by OleksandrBerchenko** [comment]
```
16 Scene id
```

Actually it's byte 8.  Also remove "on the addressed device or zone" sentence.
