### ISSUE TITLE
Decompile Lightify Android APK

### ISSUE THREAD

**Issue by dalethomas81** [noctarius/lightify-binary-protocol#6]
Today I was able to decompile the APK for the Lightify app. You can see how the protocol works clearly although the programming is not commented very well. Is this something that you are interested in having and is it appropriate to share that with you?

**Comment by noctarius** [comment]
I did decompile it a long while ago and yeah, the protocol was pretty nicely visible. Feel free to work on every bit you like. The main goal for all of us would probably be to figure out 100% of the local protocol (especially since the gateway reacts to way way more command ids than the app is using ;-)).

It'd be best to just make the changes in a fork and send pull requests, otherwise feel free to document the packets and I'll write it when I have a bit of time :)

Thanks for the help though!

**Comment by OleksandrBerchenko** [comment]
Do you have an up to date list of supported device type IDs?

Thanks!

**Comment by dalethomas81** [comment]
I only spent a couple of hours going through it last night. I am not fluent in Java so it’s taking a while to understand. I will share the progress in a fork when I get more free time. 

Also, thank you so much for the work you have done so far. It has make my home automation so much better and now that it is evident that support for this system is going away I can breathe more live into it for a bit longer. 

Regards,
Dale

**Comment by dalethomas81** [comment]
> Do you have an up to date list of supported device type IDs?
> 
> Thanks!

See my fork. I was able to find a few more device type ids.

**Comment by OleksandrBerchenko** [comment]
Are you sure about this?

```
40 | Switch (2 switches)
-- | --
41 | Switch (4 switches)
```

In noctarius documentation there are 64 and 65, and my 4-buttons switches have 65 for sure.

**Comment by OleksandrBerchenko** [comment]
0x40 = 64 and 0x41 = 65 :)

**Comment by dalethomas81** [comment]
> 0x40 = 64 and 0x41 = 65 :)

Now I need to go through and make sure everything is decimal or hex. I did this at 2am :)

**Comment by noctarius** [comment]
I think at this point the values are decimal, but most other values are hex. That said, it probably makes sense to change it all to hex :)

**Comment by dalethomas81** [comment]
That makes sense. I will take care of that. I spent a good bit of time combing through the code last night. It is very overwhelming. Methods do not have intuitive name. For example, I would name a method “IsTemperatureSupported” but they only use letters like “a” or “aK”. 

My main focus now is just going to be making my own comments as I go through. Focusing on the light parser. 

I have uploaded the code to GitHub and made it private as I don’t know if it will be ok to make it public. What are your thoughts? If I should leave it private I can invite you to the repo I think. 

Regards,
Dale

**Comment by noctarius** [comment]
The code is actually obfuscated, that means a program exchanged all method-, variable-, ...-names to make exactly one thing complicated: decompiling and reading the code ;)

And yes, you should definitely leave the code private. Decompiled or not, it is intellectual property of OSRAM / Silvana.

**Comment by dalethomas81** [comment]
Ah! I have learned something new today! That’s a neat trick on their part. 

Regards,
Dale
